// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";

export interface CloudProviderSnapshotRestoreJobDeliveryType {
    automated?: pulumi.Input<boolean>;
    download?: pulumi.Input<boolean>;
    targetClusterName?: pulumi.Input<string>;
    targetProjectId?: pulumi.Input<string>;
}

export interface ClusterAdvancedConfiguration {
    failIndexKeyTooLong?: pulumi.Input<boolean>;
    javascriptEnabled?: pulumi.Input<boolean>;
    minimumEnabledTlsProtocol?: pulumi.Input<string>;
    noTableScan?: pulumi.Input<boolean>;
    oplogSizeMb?: pulumi.Input<number>;
    sampleRefreshIntervalBiConnector?: pulumi.Input<number>;
    sampleSizeBiConnector?: pulumi.Input<number>;
}

export interface ClusterBiConnector {
    enabled?: pulumi.Input<string>;
    readPreference?: pulumi.Input<string>;
}

export interface ClusterReplicationSpec {
    id?: pulumi.Input<string>;
    numShards: pulumi.Input<number>;
    regionsConfigs?: pulumi.Input<pulumi.Input<inputs.ClusterReplicationSpecRegionsConfig>[]>;
    zoneName?: pulumi.Input<string>;
}

export interface ClusterReplicationSpecRegionsConfig {
    analyticsNodes?: pulumi.Input<number>;
    electableNodes?: pulumi.Input<number>;
    priority?: pulumi.Input<number>;
    readOnlyNodes?: pulumi.Input<number>;
    regionName?: pulumi.Input<string>;
}

export interface DatabaseUserRole {
    collectionName?: pulumi.Input<string>;
    databaseName?: pulumi.Input<string>;
    roleName?: pulumi.Input<string>;
}

export interface EncryptionAtRestAwsKms {
    accessKeyId: pulumi.Input<string>;
    customerMasterKeyId: pulumi.Input<string>;
    enabled: pulumi.Input<boolean>;
    region: pulumi.Input<string>;
    secretAccessKey: pulumi.Input<string>;
}

export interface EncryptionAtRestAzureKeyVault {
    azureEnvironment: pulumi.Input<string>;
    clientId: pulumi.Input<string>;
    enabled: pulumi.Input<boolean>;
    keyIdentifier: pulumi.Input<string>;
    keyVaultName: pulumi.Input<string>;
    resourceGroupName: pulumi.Input<string>;
    secret: pulumi.Input<string>;
    subscriptionId: pulumi.Input<string>;
    tenantId: pulumi.Input<string>;
}

export interface EncryptionAtRestGoogleCloudKms {
    enabled: pulumi.Input<boolean>;
    keyVersionResourceId: pulumi.Input<string>;
    serviceAccountKey: pulumi.Input<string>;
}

export interface ProjectIpWhitelistWhitelist {
    cidrBlock?: pulumi.Input<string>;
    comment?: pulumi.Input<string>;
    ipAddress?: pulumi.Input<string>;
}
