// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as outputs from "../types/output";

export interface CloudProviderSnapshotRestoreJobDeliveryType {
    automated?: boolean;
    download?: boolean;
    targetClusterName?: string;
    targetProjectId?: string;
}

export interface ClusterAdvancedConfiguration {
    failIndexKeyTooLong: boolean;
    javascriptEnabled: boolean;
    minimumEnabledTlsProtocol: string;
    noTableScan: boolean;
    oplogSizeMb: number;
    sampleRefreshIntervalBiConnector: number;
    sampleSizeBiConnector: number;
}

export interface ClusterBiConnector {
    enabled: string;
    readPreference: string;
}

export interface ClusterReplicationSpec {
    id: string;
    numShards: number;
    regionsConfigs: outputs.ClusterReplicationSpecRegionsConfig[];
    zoneName?: string;
}

export interface ClusterReplicationSpecRegionsConfig {
    analyticsNodes?: number;
    electableNodes: number;
    priority: number;
    readOnlyNodes?: number;
    regionName: string;
}

export interface DatabaseUserRole {
    collectionName: string;
    databaseName: string;
    roleName: string;
}

export interface EncryptionAtRestAwsKms {
    accessKeyId: string;
    customerMasterKeyId: string;
    enabled: boolean;
    region: string;
    secretAccessKey: string;
}

export interface EncryptionAtRestAzureKeyVault {
    azureEnvironment: string;
    clientId: string;
    enabled: boolean;
    keyIdentifier: string;
    keyVaultName: string;
    resourceGroupName: string;
    secret: string;
    subscriptionId: string;
    tenantId: string;
}

export interface EncryptionAtRestGoogleCloudKms {
    enabled: boolean;
    keyVersionResourceId: string;
    serviceAccountKey: string;
}

export interface ProjectIpWhitelistWhitelist {
    cidrBlock: string;
    comment: string;
    ipAddress: string;
}
