// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CloudProviderSnapshot extends pulumi.CustomResource {
    /**
     * Get an existing CloudProviderSnapshot resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CloudProviderSnapshotState, opts?: pulumi.CustomResourceOptions): CloudProviderSnapshot {
        return new CloudProviderSnapshot(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mongodbatlas:index/cloudProviderSnapshot:CloudProviderSnapshot';

    /**
     * Returns true if the given object is an instance of CloudProviderSnapshot.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CloudProviderSnapshot {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CloudProviderSnapshot.__pulumiType;
    }

    public readonly clusterName!: pulumi.Output<string>;
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    public readonly description!: pulumi.Output<string>;
    public /*out*/ readonly expiresAt!: pulumi.Output<string>;
    public /*out*/ readonly masterKeyUuid!: pulumi.Output<string>;
    public /*out*/ readonly mongodVersion!: pulumi.Output<string>;
    public readonly projectId!: pulumi.Output<string>;
    public readonly retentionInDays!: pulumi.Output<number>;
    public /*out*/ readonly snapshotId!: pulumi.Output<string>;
    public /*out*/ readonly snapshotType!: pulumi.Output<string>;
    public /*out*/ readonly status!: pulumi.Output<string>;
    public /*out*/ readonly storageSizeBytes!: pulumi.Output<number>;
    public /*out*/ readonly type!: pulumi.Output<string>;

    /**
     * Create a CloudProviderSnapshot resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CloudProviderSnapshotArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CloudProviderSnapshotArgs | CloudProviderSnapshotState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as CloudProviderSnapshotState | undefined;
            inputs["clusterName"] = state ? state.clusterName : undefined;
            inputs["createdAt"] = state ? state.createdAt : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["expiresAt"] = state ? state.expiresAt : undefined;
            inputs["masterKeyUuid"] = state ? state.masterKeyUuid : undefined;
            inputs["mongodVersion"] = state ? state.mongodVersion : undefined;
            inputs["projectId"] = state ? state.projectId : undefined;
            inputs["retentionInDays"] = state ? state.retentionInDays : undefined;
            inputs["snapshotId"] = state ? state.snapshotId : undefined;
            inputs["snapshotType"] = state ? state.snapshotType : undefined;
            inputs["status"] = state ? state.status : undefined;
            inputs["storageSizeBytes"] = state ? state.storageSizeBytes : undefined;
            inputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as CloudProviderSnapshotArgs | undefined;
            if (!args || args.clusterName === undefined) {
                throw new Error("Missing required property 'clusterName'");
            }
            if (!args || args.description === undefined) {
                throw new Error("Missing required property 'description'");
            }
            if (!args || args.projectId === undefined) {
                throw new Error("Missing required property 'projectId'");
            }
            if (!args || args.retentionInDays === undefined) {
                throw new Error("Missing required property 'retentionInDays'");
            }
            inputs["clusterName"] = args ? args.clusterName : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["projectId"] = args ? args.projectId : undefined;
            inputs["retentionInDays"] = args ? args.retentionInDays : undefined;
            inputs["createdAt"] = undefined /*out*/;
            inputs["expiresAt"] = undefined /*out*/;
            inputs["masterKeyUuid"] = undefined /*out*/;
            inputs["mongodVersion"] = undefined /*out*/;
            inputs["snapshotId"] = undefined /*out*/;
            inputs["snapshotType"] = undefined /*out*/;
            inputs["status"] = undefined /*out*/;
            inputs["storageSizeBytes"] = undefined /*out*/;
            inputs["type"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(CloudProviderSnapshot.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CloudProviderSnapshot resources.
 */
export interface CloudProviderSnapshotState {
    readonly clusterName?: pulumi.Input<string>;
    readonly createdAt?: pulumi.Input<string>;
    readonly description?: pulumi.Input<string>;
    readonly expiresAt?: pulumi.Input<string>;
    readonly masterKeyUuid?: pulumi.Input<string>;
    readonly mongodVersion?: pulumi.Input<string>;
    readonly projectId?: pulumi.Input<string>;
    readonly retentionInDays?: pulumi.Input<number>;
    readonly snapshotId?: pulumi.Input<string>;
    readonly snapshotType?: pulumi.Input<string>;
    readonly status?: pulumi.Input<string>;
    readonly storageSizeBytes?: pulumi.Input<number>;
    readonly type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CloudProviderSnapshot resource.
 */
export interface CloudProviderSnapshotArgs {
    readonly clusterName: pulumi.Input<string>;
    readonly description: pulumi.Input<string>;
    readonly projectId: pulumi.Input<string>;
    readonly retentionInDays: pulumi.Input<number>;
}
