// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class EncryptionAtRest extends pulumi.CustomResource {
    /**
     * Get an existing EncryptionAtRest resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EncryptionAtRestState, opts?: pulumi.CustomResourceOptions): EncryptionAtRest {
        return new EncryptionAtRest(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mongodbatlas:index/encryptionAtRest:EncryptionAtRest';

    /**
     * Returns true if the given object is an instance of EncryptionAtRest.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EncryptionAtRest {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EncryptionAtRest.__pulumiType;
    }

    public readonly awsKms!: pulumi.Output<outputs.EncryptionAtRestAwsKms | undefined>;
    public readonly azureKeyVault!: pulumi.Output<outputs.EncryptionAtRestAzureKeyVault | undefined>;
    public readonly googleCloudKms!: pulumi.Output<outputs.EncryptionAtRestGoogleCloudKms | undefined>;
    public readonly projectId!: pulumi.Output<string>;

    /**
     * Create a EncryptionAtRest resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EncryptionAtRestArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EncryptionAtRestArgs | EncryptionAtRestState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as EncryptionAtRestState | undefined;
            inputs["awsKms"] = state ? state.awsKms : undefined;
            inputs["azureKeyVault"] = state ? state.azureKeyVault : undefined;
            inputs["googleCloudKms"] = state ? state.googleCloudKms : undefined;
            inputs["projectId"] = state ? state.projectId : undefined;
        } else {
            const args = argsOrState as EncryptionAtRestArgs | undefined;
            if (!args || args.projectId === undefined) {
                throw new Error("Missing required property 'projectId'");
            }
            inputs["awsKms"] = args ? args.awsKms : undefined;
            inputs["azureKeyVault"] = args ? args.azureKeyVault : undefined;
            inputs["googleCloudKms"] = args ? args.googleCloudKms : undefined;
            inputs["projectId"] = args ? args.projectId : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(EncryptionAtRest.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EncryptionAtRest resources.
 */
export interface EncryptionAtRestState {
    readonly awsKms?: pulumi.Input<inputs.EncryptionAtRestAwsKms>;
    readonly azureKeyVault?: pulumi.Input<inputs.EncryptionAtRestAzureKeyVault>;
    readonly googleCloudKms?: pulumi.Input<inputs.EncryptionAtRestGoogleCloudKms>;
    readonly projectId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a EncryptionAtRest resource.
 */
export interface EncryptionAtRestArgs {
    readonly awsKms?: pulumi.Input<inputs.EncryptionAtRestAwsKms>;
    readonly azureKeyVault?: pulumi.Input<inputs.EncryptionAtRestAzureKeyVault>;
    readonly googleCloudKms?: pulumi.Input<inputs.EncryptionAtRestGoogleCloudKms>;
    readonly projectId: pulumi.Input<string>;
}
