// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class NetworkPeering extends pulumi.CustomResource {
    /**
     * Get an existing NetworkPeering resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NetworkPeeringState, opts?: pulumi.CustomResourceOptions): NetworkPeering {
        return new NetworkPeering(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mongodbatlas:index/networkPeering:NetworkPeering';

    /**
     * Returns true if the given object is an instance of NetworkPeering.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NetworkPeering {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NetworkPeering.__pulumiType;
    }

    public readonly accepterRegionName!: pulumi.Output<string>;
    public readonly atlasCidrBlock!: pulumi.Output<string>;
    public readonly atlasGcpProjectId!: pulumi.Output<string>;
    public /*out*/ readonly atlasId!: pulumi.Output<string>;
    public readonly atlasVpcName!: pulumi.Output<string>;
    public readonly awsAccountId!: pulumi.Output<string>;
    public readonly azureDirectoryId!: pulumi.Output<string>;
    public readonly azureSubscriptionId!: pulumi.Output<string>;
    public /*out*/ readonly connectionId!: pulumi.Output<string>;
    public readonly containerId!: pulumi.Output<string>;
    public /*out*/ readonly errorMessage!: pulumi.Output<string>;
    public /*out*/ readonly errorState!: pulumi.Output<string>;
    public /*out*/ readonly errorStateName!: pulumi.Output<string>;
    public readonly gcpProjectId!: pulumi.Output<string>;
    public readonly networkName!: pulumi.Output<string>;
    public /*out*/ readonly peerId!: pulumi.Output<string>;
    public readonly projectId!: pulumi.Output<string>;
    public readonly providerName!: pulumi.Output<string | undefined>;
    public readonly resourceGroupName!: pulumi.Output<string>;
    public readonly routeTableCidrBlock!: pulumi.Output<string>;
    public /*out*/ readonly status!: pulumi.Output<string>;
    public /*out*/ readonly statusName!: pulumi.Output<string>;
    public readonly vnetName!: pulumi.Output<string>;
    public readonly vpcId!: pulumi.Output<string>;

    /**
     * Create a NetworkPeering resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NetworkPeeringArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NetworkPeeringArgs | NetworkPeeringState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as NetworkPeeringState | undefined;
            inputs["accepterRegionName"] = state ? state.accepterRegionName : undefined;
            inputs["atlasCidrBlock"] = state ? state.atlasCidrBlock : undefined;
            inputs["atlasGcpProjectId"] = state ? state.atlasGcpProjectId : undefined;
            inputs["atlasId"] = state ? state.atlasId : undefined;
            inputs["atlasVpcName"] = state ? state.atlasVpcName : undefined;
            inputs["awsAccountId"] = state ? state.awsAccountId : undefined;
            inputs["azureDirectoryId"] = state ? state.azureDirectoryId : undefined;
            inputs["azureSubscriptionId"] = state ? state.azureSubscriptionId : undefined;
            inputs["connectionId"] = state ? state.connectionId : undefined;
            inputs["containerId"] = state ? state.containerId : undefined;
            inputs["errorMessage"] = state ? state.errorMessage : undefined;
            inputs["errorState"] = state ? state.errorState : undefined;
            inputs["errorStateName"] = state ? state.errorStateName : undefined;
            inputs["gcpProjectId"] = state ? state.gcpProjectId : undefined;
            inputs["networkName"] = state ? state.networkName : undefined;
            inputs["peerId"] = state ? state.peerId : undefined;
            inputs["projectId"] = state ? state.projectId : undefined;
            inputs["providerName"] = state ? state.providerName : undefined;
            inputs["resourceGroupName"] = state ? state.resourceGroupName : undefined;
            inputs["routeTableCidrBlock"] = state ? state.routeTableCidrBlock : undefined;
            inputs["status"] = state ? state.status : undefined;
            inputs["statusName"] = state ? state.statusName : undefined;
            inputs["vnetName"] = state ? state.vnetName : undefined;
            inputs["vpcId"] = state ? state.vpcId : undefined;
        } else {
            const args = argsOrState as NetworkPeeringArgs | undefined;
            if (!args || args.containerId === undefined) {
                throw new Error("Missing required property 'containerId'");
            }
            if (!args || args.projectId === undefined) {
                throw new Error("Missing required property 'projectId'");
            }
            inputs["accepterRegionName"] = args ? args.accepterRegionName : undefined;
            inputs["atlasCidrBlock"] = args ? args.atlasCidrBlock : undefined;
            inputs["atlasGcpProjectId"] = args ? args.atlasGcpProjectId : undefined;
            inputs["atlasVpcName"] = args ? args.atlasVpcName : undefined;
            inputs["awsAccountId"] = args ? args.awsAccountId : undefined;
            inputs["azureDirectoryId"] = args ? args.azureDirectoryId : undefined;
            inputs["azureSubscriptionId"] = args ? args.azureSubscriptionId : undefined;
            inputs["containerId"] = args ? args.containerId : undefined;
            inputs["gcpProjectId"] = args ? args.gcpProjectId : undefined;
            inputs["networkName"] = args ? args.networkName : undefined;
            inputs["projectId"] = args ? args.projectId : undefined;
            inputs["providerName"] = args ? args.providerName : undefined;
            inputs["resourceGroupName"] = args ? args.resourceGroupName : undefined;
            inputs["routeTableCidrBlock"] = args ? args.routeTableCidrBlock : undefined;
            inputs["vnetName"] = args ? args.vnetName : undefined;
            inputs["vpcId"] = args ? args.vpcId : undefined;
            inputs["atlasId"] = undefined /*out*/;
            inputs["connectionId"] = undefined /*out*/;
            inputs["errorMessage"] = undefined /*out*/;
            inputs["errorState"] = undefined /*out*/;
            inputs["errorStateName"] = undefined /*out*/;
            inputs["peerId"] = undefined /*out*/;
            inputs["status"] = undefined /*out*/;
            inputs["statusName"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(NetworkPeering.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NetworkPeering resources.
 */
export interface NetworkPeeringState {
    readonly accepterRegionName?: pulumi.Input<string>;
    readonly atlasCidrBlock?: pulumi.Input<string>;
    readonly atlasGcpProjectId?: pulumi.Input<string>;
    readonly atlasId?: pulumi.Input<string>;
    readonly atlasVpcName?: pulumi.Input<string>;
    readonly awsAccountId?: pulumi.Input<string>;
    readonly azureDirectoryId?: pulumi.Input<string>;
    readonly azureSubscriptionId?: pulumi.Input<string>;
    readonly connectionId?: pulumi.Input<string>;
    readonly containerId?: pulumi.Input<string>;
    readonly errorMessage?: pulumi.Input<string>;
    readonly errorState?: pulumi.Input<string>;
    readonly errorStateName?: pulumi.Input<string>;
    readonly gcpProjectId?: pulumi.Input<string>;
    readonly networkName?: pulumi.Input<string>;
    readonly peerId?: pulumi.Input<string>;
    readonly projectId?: pulumi.Input<string>;
    readonly providerName?: pulumi.Input<string>;
    readonly resourceGroupName?: pulumi.Input<string>;
    readonly routeTableCidrBlock?: pulumi.Input<string>;
    readonly status?: pulumi.Input<string>;
    readonly statusName?: pulumi.Input<string>;
    readonly vnetName?: pulumi.Input<string>;
    readonly vpcId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a NetworkPeering resource.
 */
export interface NetworkPeeringArgs {
    readonly accepterRegionName?: pulumi.Input<string>;
    readonly atlasCidrBlock?: pulumi.Input<string>;
    readonly atlasGcpProjectId?: pulumi.Input<string>;
    readonly atlasVpcName?: pulumi.Input<string>;
    readonly awsAccountId?: pulumi.Input<string>;
    readonly azureDirectoryId?: pulumi.Input<string>;
    readonly azureSubscriptionId?: pulumi.Input<string>;
    readonly containerId: pulumi.Input<string>;
    readonly gcpProjectId?: pulumi.Input<string>;
    readonly networkName?: pulumi.Input<string>;
    readonly projectId: pulumi.Input<string>;
    readonly providerName?: pulumi.Input<string>;
    readonly resourceGroupName?: pulumi.Input<string>;
    readonly routeTableCidrBlock?: pulumi.Input<string>;
    readonly vnetName?: pulumi.Input<string>;
    readonly vpcId?: pulumi.Input<string>;
}
